services:
  broker:
    build:
      context: ./broker
    ports:
      - "8080:8080"
    networks:
      - dist_net

  client:
    build:
      context: ./client
    ports:
      - "8083:8083"
    networks:
      - dist_net

  node1:
    build:
      context: ./node
    environment:
      - NODE_PORT=8081
    ports:
      - "8081:8081"
    networks:
      - dist_net
    depends_on:
      - broker
    volumes:
      - ./node/src/main/resources/videos:/app/videos:rw

  node2:
    build:
      context: ./node
    environment:
      - NODE_PORT=8082
    ports:
      - "8082:8081"
    networks:
      - dist_net
    depends_on:
      - broker
    volumes:
      - ./node/src/main/resources/videos:/app/videos:rw

  node3:
    build:
      context: ./node
    environment:
      - NODE_PORT=8084
    ports:
      - "8084:8081"
    networks:
      - dist_net
    depends_on:
      - broker
    volumes:
      - ./node/src/main/resources/videos:/app/videos:rw

  node4:
    build:
      context: ./node
    environment:
      - NODE_PORT=8085
    ports:
      - "8085:8081"
    networks:
      - dist_net
    depends_on:
      - broker
    volumes:
      - ./node/src/main/resources/videos:/app/videos:rw

  node5:
    build:
      context: ./node
    environment:
      - NODE_PORT=8086
    ports:
      - "8086:8081"
    networks:
      - dist_net
    depends_on:
      - broker
    volumes:
      - ./node/src/main/resources/videos:/app/videos:rw
  node6:
    build:
      context: ./node
    environment:
      - NODE_PORT=8087
    ports:
      - "8087:8081"
    networks:
      - dist_net
    depends_on:
      - broker
    volumes:
      - ./node/src/main/resources/videos:/app/videos:rw

networks:
  dist_net:
    driver: bridge
