video.storage.path=src/main/resources/videos
server.port=${port:8081}
logging.level.sharktank=DEBUG
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n
broker.url=http://broker:8080

# Increased timeouts
spring.mvc.async.request-timeout=300000
server.tomcat.connection-timeout=300000
spring.servlet.multipart.max-request-size=1000MB
spring.servlet.multipart.max-file-size=1000MB
spring.output.ansi.enabled=ALWAYS